# Generated by Django 3.0.7 on 2020-07-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_xl'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo5',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='photo6',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xl',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='xl',
            name='contry',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='xl',
            name='ip',
            field=models.TextField(null=True),
        ),
    ]
